# Generated by Django 4.2.23 on 2025-08-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('applicants', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicants.applicantprofile'),
        ),
        migrations.DeleteModel(
            name='ApplicantProfile',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
